services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sgi-app
    container_name: sgi-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - redis

  web:
    image: nginx:alpine
    container_name: sgi-web
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/ssl/certificate.crt:/etc/nginx/ssl/certificate.crt
      - ./public/ssl/private.key:/etc/nginx/ssl/private.key
      - .:/var/www
    depends_on:
      - app

  redis:
    image: redis:latest
    container_name: laravel-redis
    ports:
      - "6379:6379"
    restart: always

  queue:
    image: sgi-app
    container_name: sgi-queue
    command: php artisan queue:work redis --timeout=60 --tries=3
    depends_on:
      - app
      - redis
    volumes:
      - .:/var/www
    restart: always